### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by kazumaxneo** [rkajitani/MetaPlatanus#1]
Hi, 

I would like to use MetaPlatanus to assemble my metagenome sample. However,  when I run MetaPlatanus using the perl wrapper, I get the following error. 
How can I run correctly? 
My os is ubuntu18.04 with AMD threadripper 3990x installed.
MetaPlatanus Linux binary was downloaded from HP (http://platanus.bio.titech.ac.jp/metaplatanus)

$ perl meta_platanus.pl cons_asm --IP1 pair_R1.fq pair_R2.fq --o outprefix --t 20
Inappropriate ioctl for device

**Comment by rkajitani** [comment]
Thank you for the report and sorry for the late replying.
This bug occurs when a string other than "out" is specified with `-o` (e.g., `--o outprefix`).
 As a temporary solution, please specify `--o out`, or use the next version: v1.2.3 (https://github.com/rkajitani/MetaPlatanus/releases).

I know that this tool is not user-friendly, and I will release a new version (v1.3.0) with a Bioconda package.

**Comment by kazumaxneo** [comment]
Hi, rkajitani.

Thanks for the advice.
I was able to run MetaPlatanus by setting  "--o out".
I'm looking forward to trying next version,

best,
