### ISSUE TITLE
Read file exception!!

### ISSUE THREAD

**Issue by kangxiongbin** [rkajitani/MetaPlatanus#10]
Dear Rkajitani,
I'm interested in your MetaPlatanus. Recently I run it and encouter a issue.

**Command: metaplatanus -IP1 r1.fq r2.fq -ont long_10x_2.fq > log.txt 2>&1**
**MetaPlatanus version: 1.3.0
Error(2): Error, Read file exception!!
Read file exception!!
Read file is not FASTA/FASTQ format.
Command exited with non-zero status 2
1.63user 0.43system 0:02.07elapsed 99%CPU (0avgtext+0avgdata 19988maxresident)k
0inputs+927960outputs (0major+28471minor)pagefaults 0swaps**

My paired-end reads:
r1.fq:
![image](https://user-images.githubusercontent.com/23208764/161008743-40e66c98-24eb-4b9f-af05-5937526a1063.png)

r2.fq:
![image](https://user-images.githubusercontent.com/23208764/161008829-27c440b1-1f0a-4087-9971-c9c387689c6f.png)

Do you know how to address the problem? Thank you very much!

**Comment by kangxiongbin** [comment]
**When I download your test data and run the default command: https://github.com/rkajitani/MetaPlatanus/tree/master/test_data
Encounter new problem:**

AVE_READ_LEN=100
K = 25, saving kmers from reads...

#### PROCESS INFORMATION ####
VmPeak:          95.761 GByte
VmHWM:            0.387 GByte
6.98user 23.45system 0:31.94elapsed 95%CPU (0avgtext+0avgdata 100406132maxresident)k
0inputs+928outputs (0major+25105612minor)pagefaults 0swaps

**Comment by rkajitani** [comment]
Thank you for reporting!
Lower cases such as "g" causes the error.
Temporarily, the error can be avoided replacing lower cases with upper cases. An easy way is to use `seqkit seq -w0 -u`.
In addition, I fix the code to ignore lower cases, and you can use updated metaplatanus_core (executable).
```
git clone https://github.com/rkajitani/MetaPlatanus.git
cd MetaPlatanus/src/metaplatanus_core
make
cp metaplatnaus_core /metaplatanus-installation-path/sub_bin/
```

**Comment by kangxiongbin** [comment]
Thank you very much! It works.
