### ISSUE TITLE
Inappropriate ioctl for device on docker

### ISSUE THREAD

**Issue by YuyaKiguchi** [rkajitani/MetaPlatanus#2]
Hi,

I use metaplatanus v1.3.0 by docker and got the same issue of https://github.com/rkajitani/MetaPlatanus/issues/1#issue-918384122

`docker run -v $PWD:/data --rm rkajitani/metaplatanus metaplatanus  -IP1 R1.fastq.gz R2.fastq.gz -p pacbio.fasta --o out -t 50 > log 2>&1`

Could you solve the problem?

Yuya

**Comment by rkajitani** [comment]
Thank you for reporting.
I have fixed the image in [DockerHub](https://hub.docker.com/repository/docker/rkajitani/metaplatanus).

As a command, you will need to specify file names with **/data** .
`docker run -v $PWD:/data --rm rkajitani/metaplatanus metaplatanus -IP1 /data/R1.fastq.gz /data/R2.fastq.gz -p /data/pacbio.fasta --o out -t 50 > log 2>&1
`
I hope you re-pull the docker image and try the command above.
Sorry for bothering you.

**Comment by Unaimend** [comment]
I had the same error with the conda installation

**Comment by rkajitani** [comment]
Thank you for informing! I will improve the usability...
