### ISSUE TITLE
metaplatanus fails in 3_binning (Error: 256 binning (metabat2) error!)

### ISSUE THREAD

**Issue by mistergroot** [rkajitani/MetaPlatanus#6]
Hello! 

I hope you are well. I am trying to do a hybrid metagenome assembly using an Illumina 2x150bp library and an ONT library. I am unsure why, but the assembly consistently fails on step 3, throwing an error to the log file that reads:

`metaplatanus version v1.3.0

Error: 256 binning (metabat2) error!
File exists`

My installation is directly from bioconda (following instructions from the readme) in a clean environment. It seems others have not had this issue with the latest version of metaplatanus so I am not quite sure what is causing this. I am running this on my university's PBS Torque system and am running exclusively on the open allocation. Therefore, I run into walltime restraints and resume the job whenever walltime limits are reached and I am wondering if perhaps resuming the assembly is causing issues with files already existing. Do you have any recommendations on things to try to resolve this?

Any help would be much appreciated!

-Nick

**Comment by rkajitani** [comment]
Thank you for the report.
Could you please show or attach the log files below?
```
out_intermediate/3_binning/jgi_summarize_bam_contig_depths.log
out_intermediate/3_binning/metabat2.stderr
```

I'm sorry to bother you.

**Comment by mistergroot** [comment]
Not a bother at all, I appreciate your help! 
It does not appear that metabat2.stderr exists. The jgi_summarize_bam_contig_depths.log reads as follows:

`/usr/bin/time: cannot run jgi_summarize_bam_contig_depths: No such file or directory
0.00user 0.00system 0:00.01elapsed 12%CPU (0avgtext+0avgdata 360maxresident)k
0inputs+0outputs (0major+77minor)pagefaults 0swaps`

It does not seem to be able to find jgi_summarize_bam_contig_depths at this step despite it being installed in the environment.

**Comment by mistergroot** [comment]
I simply added jgi_summarize_bam_contig_depths to my path and it seems to be working fine now. I'm not sure if this is an issue with my specific installation or an issue with conda installation in general but this seems to be a fine workaround if others end up having the same issue.

**Comment by rkajitani** [comment]
Thank you for fixing your environment.
As you mentioned, the metaplatanus conda package is bundled with metabat2 and jgi_summarize_bam_contig_depths is automatically installed. In addition, metaplatanus checks the dependencies (commands) when executed. So I have been thinking about the cause of this issue.
If your environment is broken for some reason, you should (1) add jgi_summarize_bam_contig_depths to your path (as you did), (2) re-install metaplatanus package (`conda install metaplatanus`), or (3) re-install metabat2 package (`conda install metabat2`).
Anyway, I hope your process will succeed!

**Comment by mistergroot** [comment]
Metaplatanus appears to have successfully output an assembly after adding jgi_summarize_bam_contig_depths to my path. Thank you for your help! Happy holidays!
