### ISSUE TITLE
Error: contig_assembly error! Function not implemented

### ISSUE THREAD

**Issue by Krasnopeev** [rkajitani/MetaPlatanus#7]
Hi!

MetaPlatanus was installed with conda as described in manual without any issues.

I used PE 2x200bp Illumina reads and run ended with error.
Here is log file content:
```
Error: contig_assembly error!
Function not implemented
```

used command:
```
metaplatanus -IP1 BFR_R1_paired.fq BFR_R2_paired.fq -o metaplat_out -t 10 >log.txt 2>&1
```

also here is log file from folder `metaplat_out_intermediate`
[metaplat_out.assembleLog.txt](https://github.com/rkajitani/MetaPlatanus/files/7986938/metaplat_out.assembleLog.txt)

How to resolve it?
Thanks!

**Comment by rkajitani** [comment]
Thank you for reporting.
Unfortunately, MetaPlatanus requires more memory than it could use. A memory limit can be specified by -m option (default,  0.75 * available_memory), and MetaPlatanus used "-m 18.75" in your environment. So, more memory (RAM) amount may be needed to finish the assembly of your data.
A larger value of "-min_cov_contig" option will reduce the memory usage, but the size of the resulting assembly will also decrease.
I'm sorry to bother you.

**Comment by Krasnopeev** [comment]
> 

Oh, ok! I will try with different memory options. thanks!
